error: The requested endpoint could not be found, or you don't have access to it. Please check the provided ID and try again.
    at /home/runner/workspace/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PGStore._asyncQuery (/home/runner/workspace/node_modules/connect-pg-simple/index.js:322:21)
    at async PGStore._rawEnsureSessionStoreTable (/home/runner/workspace/node_modules/connect-pg-simple/index.js:177:19)
    at async PGStore._asyncQuery (/home/runner/workspace/node_modules/connect-pg-simple/index.js:315:7)
error: The requested endpoint could not be found, or you don't have access to it. Please check the provided ID and try again.
    at /home/runner/workspace/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PGStore._asyncQuery (/home/runner/workspace/node_modules/connect-pg-simple/index.js:322:21)
    at async PGStore._rawEnsureSessionStoreTable (/home/runner/workspace/node_modules/connect-pg-simple/index.js:177:19)
    at async PGStore._asyncQuery (/home/runner/workspace/node_modules/connect-pg-simple/index.js:315:7)
PostgresError: The requested endpoint could not be found, or you don't have access to it. Please check the provided ID and try again.
    at ErrorResponse (file:///home/runner/workspace/node_modules/postgres/src/connection.js:788:26)
    at handle (file:///home/runner/workspace/node_modules/postgres/src/connection.js:474:6)
    at TLSSocket.data (file:///home/runner/workspace/node_modules/postgres/src/connection.js:315:9)
    at TLSSocket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:191:23) {
  severity_local: 'ERROR',
  code: 'XX000'
}
